import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import "@shared/scss/main.scss";
import Header from "@widgets/header/Header";
import FooterMobile from "@widgets/footer/components/FooterMobile";
import QueryProvider from "src/core/providers/query/QueryProvider";
import TasksServerProvider from "src/core/providers/users/TasksServerProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <TasksServerProvider>
          <body className={inter.className}>
            {/* <SideBar /> */}

            <Header />
            <main className="min-h-screen">{children}</main>

            <FooterMobile />
          </body>
        </TasksServerProvider>
      </QueryProvider>
    </html>
  );
}
